services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    env_file:
      - .env
    
    volumes:
      - /app/node_modules

    restart: always
    
    ports:
      - 3000:3000

    networks:
      - frontend_net

    develop:
      watch:
        - action: sync
          path: ./next-app
          target: /app
          ignore: 
            - node_modules/
        - action: rebuild
          path: ./next-app/package.json


networks:
  frontend_net:
    external: true