services:
  next-app:
    container_name: next-app
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile

    env_file:
      - .env
    
    volumes:
      - ..:/app

    restart: always
    ports:
      - 3000:3000
    networks:
      - frontend_net
    
networks:
  frontend_net:
    external: true